/**
 * Playable windows of the continuous world map.
 *
 * These GameMapTypes are generated by scripts/world/build-world.ts from the
 * world pipeline's LOD-0 data (not the Go map generator). When one of them
 * is played, the client streams the rest of the Earth around the game map
 * (see WorldBackdrop) using the window's LOD-0 origin recorded in
 * resources/world/world-index.json (`windows[].gameMap` holds the
 * GameMapType key).
 */
import { GameMapType } from "../game/Game";

export const WORLD_WINDOW_MAPS: ReadonlySet<GameMapType> = new Set([
  GameMapType.WorldOceania,
]);

/** GameMapType key (e.g. "WorldOceania") for a world-window map, else null. */
export function worldWindowKey(map: GameMapType): string | null {
  if (!WORLD_WINDOW_MAPS.has(map)) return null;
  return (
    Object.keys(GameMapType).find(
      (k) => GameMapType[k as keyof typeof GameMapType] === map,
    ) ?? null
  );
}
